CREATE TABLE book (
                      id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                      title VARCHAR(45) NOT NULL
);

INSERT INTO book VALUES
(0, 'Crimen y Castigo'),
(0, 'Cien Años de Soledad');

CREATE TABLE book_page (
                           id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                           content text NOT NULL,
                           book_id INT,
                           FOREIGN KEY (book_id) REFERENCES book(id)
);

INSERT INTO book_page VALUES
#Crimen y Castigo
(0, 'Una tarde extremadamente calurosa de principios de julio, un joven salió de la reduci- da habitación que tenía alquilada en la callejue- la de S... y, con paso lento e indeciso, se dirigió al puente K...
Había tenido la suerte de no encontrarse con su patrona en la escalera.
Su cuartucho se hallaba bajo el tejado de un gran edificio de cinco pisos y, más que una habitación, parecía una alacena. En cuanto a la patrona, que le había alquilado el cuarto con servicio y pensión, ocupaba un departamento del piso de abajo; de modo que nuestro joven, cada vez que salía, se veía obligado a pasar por delante de la puerta de la cocina, que daba a la', 1),
(0, 'escalera y estaba casi siempre abierta de par en par. En esos momentos experimentaba invaria- blemente una sensación ingrata de vago temor, que le humillaba y daba a su semblante una expresión sombría. Debía una cantidad consi- derable a la patrona y por eso temía encontrar- se con ella. No es que fuera un cobarde ni un hombre abatido por la vida. Por el contrario, se hallaba desde hacía algún tiempo en un estado de irritación, de tensión incesante, que rayaba en la hipocondría. Se había habituado a vivir tan encerrado en sí mismo, tan aislado, que no sólo temía encontrarse con su patrona, sino que rehuía toda relación con sus semejantes. La pobreza le abrumaba. Sin embargo, últimamen- te esta miseria había dejado de ser para él un sufrimiento. El joven había renunciado a todas sus ocupaciones diarias, a todo trabajo.
En el fondo, se mofaba de la patrona y de todas las intenciones que pudiera abrigar contra él, pero detenerse en la escalera para oír sandeces y vulgaridades, recriminaciones, que-', 1),
(0, 'jas, amenazas, y tener que contestar con evasi- vas, excusas, embustes... No, más valía desli- zarse por la escalera como un gato para pasar inadvertido y desaparecer.
Aquella tarde, el temor que experimen- taba ante la idea de encontrarse con su acreedo- ra le llenó de asombro cuando se vio en la calle.
«¡Que me inquieten semejantes menu- dencias cuando tengo en proyecto un negocio tan audaz! -pensó con una sonrisa extraña-. Sí, el hombre lo tiene todo al alcance de la mano, y, como buen holgazán, deja que todo pase ante sus mismas narices... Esto es ya un axioma... Es chocante que lo que más temor inspira a los hombres sea aquello que les aparta de sus cos- tumbres. Sí, eso es lo que más los altera... ¡Pero esto ya es demasiado divagar! Mientras divago, no hago nada. Y también podría decir que no hacer nada es lo que me lleva a divagar. Hace ya un mes que tengo la costumbre de hablar conmigo mismo, de pasar días enteros echado', 1),
(0, 'en mi rincón, pensando... Tonterías... Porque ¿qué necesidad tengo yo de dar este paso? ¿Soy verdaderamente capaz de hacer... "eso"? ¿Es que, por lo menos, lo he pensado en serio? De ningún modo: todo ha sido un juego de mi imaginación, una fantasía que me divierte... Un juego, sí; nada más que un juego.»
El calor era sofocante. El aire irrespira- ble, la multitud, la visión de los andamios, de la cal, de los ladrillos esparcidos por todas partes, y ese hedor especial tan conocido por los pe- tersburgueses que no disponen de medios para alquilar una casa en el campo, todo esto au- mentaba la tensión de los nervios, ya bastante excitados, del joven. El insoportable olor de las tabernas, abundantísimas en aquel barrio, y los borrachos que a cada paso se tropezaban a pe- sar de ser día de trabajo, completaban el lasti- moso y horrible cuadro. Una expresión de amargo disgusto pasó por las finas facciones del joven. Era, dicho sea de paso, extraordina- riamente bien parecido, de una talla que reba-', 1),


#Cien Ańos de Soledad
(0, 'Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Macondo era entonces una aldea de veinte casas de barro y cañabrava construidas a la orilla de un río de aguas diáfanas que se precipitaban por un lecho de piedras pulidas, blancas y enormes como huevos prehistóricos. El mundo era tan reciente, que muchas cosas carecían de nombre, y para mencionarlas había que señalarías con el dedo. Todos los años, por el mes de marzo, una familia de gitanos desarrapados plantaba su carpa cerca de la aldea, y con un grande alboroto de pitos y timbales daban a conocer los nuevos inventos. Primero llevaron el imán. Un gitano corpulento, de barba montaraz y manos de gorrión, que se presentó con el nombre de Melquiades, hizo una truculenta demostración pública de lo que él mismo llamaba la octava maravilla de los sabios alquimistas de Macedonia. Fue de casa en casa arrastrando dos lingotes metálicos, y todo el mundo se espantó al ver que los calderos, las pailas, las tenazas y los anafes se caían de su sitio, y las maderas crujían por la desesperación de los clavos y los tornillos tratando de desenclavarse, y aun los objetos perdidos desde hacía mucho tiempo aparecían por donde más se les había buscado, y se arrastraban en desbandada turbulenta detrás de los fierros mágicos de Melquíades. «Las cosas, tienen vida propia -pregonaba el gitano con áspero acento-, todo es cuestión de despertarles el ánima.» José Arcadio Buendía, cuya desaforada imaginación iba siempre más lejos que el ingenio de la naturaleza, y aun más allá del milagro y la magia, pensó que era posible servirse de aquella invención inútil para desentrañar el oro de la tierra. Melquíades, que era un hombre honrado, le previno: «Para eso no sirve.» Pero José Arcadio Buendía no creía en aquel tiempo en la honradez de los gitanos, así que cambió su mulo y una partida de chivos por los dos lingotes imantados. Úrsula Iguarán, su mujer, que contaba con aquellos animales para ensanchar el desmedrado patrimonio doméstico, no consiguió disuadirlo. «Muy pronto ha de sobrarnos oro para empedrar la casa», replicó su marido. Durante varios meses se empeñó en demostrar el acierto de sus conjeturas. Exploró palmo a palmo la región, inclusive el fondo del río, arrastrando los dos lingotes de hierro y recitando en voz alta el conjuro de Melquíades. Lo único que logró', 2),
(0, 'desenterrar fue una armadura del siglo xv con todas sus partes soldadas por un cascote de óxido, cuyo interior tenía la resonancia hueca de un enorme calabazo lleno de piedras. Cuando José Arcadio Buendía y los cuatro hombres de su expedición lograron desarticular la armadura, encontraron dentro un esqueleto calcificado que llevaba colgado en el cuello un relicario de cobre con un rizo de mujer.
En marzo volvieron los gitanos. Esta vez llevaban un catalejo y una lupa del tamaño de un tambor, que exhibieron como el último descubrimiento de los judíos de Amsterdam. Sentaron una gitana en un extremo de la aldea e instalaron el catalejo a la entrada de la carpa. Mediante el pago de cinco reales, la gente se asomaba al catalejo y veía a la gitana al alcance de su mano. «La ciencia ha eliminado las distancias», pregonaba Melquíades. «Dentro de poco, el hombre podrá ver lo que ocurre en cualquier lugar de la tierra, sin moverse de su casa.» Un mediodía ardiente hicieron una asombrosa demostración con la lupa gigantesca: pusieron un montón de hierba seca en mitad de la calle y le prendieron fuego mediante la concentración de los rayos solares. José Arcadio Buendía, que aún no acababa de consolarse por el fracaso de sus imanes, concibió la idea de utilizar aquel invento como un arma de guerra. Melquíades, otra vez, trató de disuadirlo. Pero terminó por aceptar los dos lingotes imantados y tres piezas de dinero colonial a cambio de la lupa. Úrsula lloró de consternación. Aquel dinero formaba parte de un cofre de monedas de oro que su padre había acumulado en toda una vida de privaciones, y que ella había enterrado debajo de la cama en espera de una buena ocasión para invertirías. José Arcadio Buendía no trató siquiera de consolarla, entregado por entero a sus experimentos tácticos con la abnegación de un científico y aun a riesgo de su propia vida. Tratando de demostrar los efectos de la lupa en la tropa enemiga, se expuso él mismo a la concentración de los rayos solares y sufrió quemaduras que se convirtieron en úlceras y tardaron mucho tiempo en sanar. Ante las protestas de su mujer, alarmada por tan peligrosa inventiva, estuvo a punto de incendiar la casa. Pasaba largas horas en su cuarto, haciendo cálculos sobre las posibilidades estratégicas de su arma novedosa, hasta que logró componer un manual de una asombrosa claridad didáctica y un poder de convicción irresistible. Lo envió a las autoridades acompañado de numerosos testimonios sobre sus experiencias y de varios pliegos de dibujos explicativos, al cuidado de un mensajero que atravesó la sierra, y se extravió en pantanos desmesurados, remontó ríos tormentosos y estuvo a punto de perecer bajo el azote de las fieras, la desesperación y la peste, antes de conseguir una ruta de enlace con las mulas del correo. A pesar de que el viaje a la capital era en aquel tiempo poco menos que imposible, José Arcadio Buendia prometía intentarlo tan pronto como se lo ordenara el gobierno, con el fin de hacer demostraciones prácticas de', 2),
(0, 'su invento ante los poderes militares, y adiestrarlos personalmente en las complicadas artes de la guerra solar. Durante varios años esperó la respuesta. Por último, cansado de esperar, se lamentó ante Melquíades del fracaso de su iniciativa, y el gitano dio entonces una prueba convincente de honradez: le devolvió los doblones a cambio de la lupa, y le dejó además unos mapas portugueses y varios instrumentos de navegación. De su puño y letra escribió una apretada síntesis de los estudios del monje Hermann, que dejó a su disposición para que pudiera servirse del astrolabio, la brújula y el sextante. José Arcadio Buendía pasó los largos meses de lluvia encerrado en un cuartito que construyó en el fondo de la casa para que nadie perturbara sus experimentos. Habiendo abandonado por completo las obligaciones domésticas, permaneció noches enteras en el patio vigilando el curso de los astros, y estuvo a punto de contraer una insolación por tratar de establecer un método exacto para encontrar el mediodía. Cuando se hizo experto en el uso y manejo de sus instrumentos, tuvo una noción del espacio que le permitió navegar por mares incógnitos, visitar territorios deshabitados y trabar relación con seres espléndidos, sin necesidad de abandonar su gabinete. Fue ésa la época en que adquirió el hábito de hablar a solas, paseándose por la casa sin hacer caso de nadie, mientras Úrsula y los niños se partían el espinazo en la huerta cuidando el plátano y la malanga, la yuca y el ñame, la ahuyama y la berenjena. De pronto, sin ningún anuncio, su actividad febril se interrumpió y fue sustituida por una especie de fascinación. Estuvo varios días como hechizado, repitiéndose a sí mismo en voz baja un sartal de asombrosas conjeturas, sin dar crédito a su propio entendimiento. Por fin, un martes de diciembre, a la hora del almuerzo, soltó de un golpe toda la carga de su tormento. Los niños habían de recordar por el resto de su vida la augusta solemnidad con que su padre se sentó a la cabecera de la mesa, temblando de fiebre, devastado por la prolongada vigilia y por el encono de su imaginación, y les reveló su descubrimiento.
-La tierra es redonda como una naranja.
Úrsula perdió la paciencia. «Si has de volverte loco, vuélvete tú solo - gritó-. Pero no trates de inculcar a los niños tus ideas de gitano.» José Arcadio Buendía, impasible, no se dejó amedrentar por la desesperación de su mujer, que en un rapto de cólera le destrozó el astrolabio contra el suelo. Construyó otro, reunió en el cuartito a los hombres del pueblo y les demostró, con teorías que para todos resultaban incomprensibles, la posibilidad de regresar al punto de partida navegando siempre hacia el Oriente. Toda la aldea estaba convencida de que José Arcadio Buendía había perdido el juicio, cuando llegó Melquíades a poner las cosas en su punto. Exaltó en público la inteligencia de aquel hombre que por pura especulación astronómica había construido una teoría ya comprobada en la práctica, aunque desconocida hasta entonces en Macondo, y como', 2),
(0, 'una prueba de su admiración le hizo un regalo que había de ejercer una influencia terminante en el futuro de la aldea: un laboratorio de alquimia.
Para esa época, Melquíades había envejecido con una rapidez asombrosa. En sus primeros viajes parecía tener la misma edad de José Arcadio Buendia. Pero mientras éste conservaba su fuerza descomunal, que le permitía derribar un caballo agarrándolo por las orejas, el gitano parecía estragado por una dolencia tenaz. Era, en realidad, el resultado de múltiples y raras enfermedades contraídas en sus incontables viajes alrededor del mundo. Según él mismo le contó a José Arcadio Buendia mientras lo ayudaba a montar el laboratorio, la muerte lo seguía a todas partes, husmeándole los pantalones, pero sin decidirse a darle el zarpazo final. Era un fugitivo de cuantas plagas y catástrofes habían flagelado al género humano. Sobrevivió a la pelagra en Persia, al escorbuto en el archipiélago de Malasia, a la lepra en Alejandría, al beriberi en el Japón, a la peste bubónica en Madagascar, al terremoto de Sicilia y a un naufragio multitudinario en el estrecho de Magallanes. Aquel ser prodigioso que decía poseer las claves de Nostradamus, era un hombre lúgubre, envuelto en un aura triste, con una mirada asiática que parecía conocer el otro lado de las cosas. Usaba un sombrero grande y negro, como las alas extendidas de un cuervo, y un chaleco de terciopelo patinado por el verdín de los siglos. Pero a pesar de su inmensa sabiduría y de su ámbito misterioso, tenía un peso humano, una condición terrestre que lo mantenía enredado en los minúsculos problemas de la vida cotidiana. Se quejaba de dolencias de viejo, sufría por los más insignificantes percances económicos y había dejado de reír desde hacía mucho tiempo, porque el escorbuto le había arrancado los dientes. El sofocante mediodía en que reveló sus secretos, José Arcadio Buendía tuvo la certidumbre de que aquél era el principio de una grande amistad. Los niños se asombraron con sus relatos fantásticos. Aureliano, que no tenía entonces más de cinco años, había de recordarlo por el resto de su vida como lo vio aquella tarde, sentado contra la claridad metálica y reverberante de la ventana, alumbrando con su pro-funda voz de órgano los territorios más oscuros de la imaginación, mientras chorreaba por sus sienes la grasa derretida por el calor. José Arcadio, su hermano mayor, había de transmitir aquella imagen maravillosa, como un recuerdo hereditario, a toda su descendencia. Úrsula, en cambio, conservó un mal recuerdo de aquella visita, porque entró al cuarto en el momento en que Melquíades rompió por distracción un frasco de bicloruro de mercurio.', 2);